---
title: 'Caracterització de pacients DM2 incidents i diferencia entre generes'
author: "Jordi Real"
website: "https://github.com/USR-DAPCAT/"

date: "`r format(Sys.time(), '%d %B, %Y')`"


---



```{r setup, include = FALSE,echo=FALSE}
knitr::opts_chunk$set(echo=F,message=F,warning=F)

library(dplyr)
library(compareGroups)
library(table1)


conductor<-here::here("conductor.xls")


```



```{r lectura_dades}

dades_prematch <- readRDS(here::here("dades/mostra","dt_prematch.Rds"))

```



# Descriptiu exploratori de variables generades 



```{r descriptiva ,include=TRUE}


# formu<-formula.text("Taula1",y="sexe",taulavariables = conductor)
 
# descrTable(formu,data=dades_prematch,extra.labels = c("","",""), hide = "No",show.p.overall = F,show.n = T) %>% 
#   export2md()

descrTable(sexe ~ age + age_cat4 + age_cat5 +DG.AP + DG.AVC_H + DG.AVC_NH + DG.CI + 
           DG.DIS + DG.HTA + DG.IC + DG.AVC + DG.PrevSec + FF.ALTRES_AAG + FF.ALTRESDIS + FF.ALTRESHTA +
           FF.ANT_VITK + FF.ANTCA + FF.ARA2 + FF.BBK + FF.BG_Metformina + FF.CLOPI + FF.DIPI + FF.DIURETIC +
           FF.ESTATINA + FF.ESTATINA_COMB + FF.EZE + FF.FIBRAT + FF.IECA + FF.AAG + FF.ANTIHTA + FF.HIPOLIP +
           ALCOHOL.valor + CAC.valor + cHDL.valor + CKDEPI.valor + cLDL.valor + CREATININA.valor + cT.valor +
           EXCPROTEINA.valor + GLICADA.valor + GLUCOSA.valor + IMC.valor + IMC.valor.cat5 + PAD.valor +
           PAS.valor + PES.valor + TALLA.valor + TG.valor + score2 + regicor + PA_cat + HBA1C7_cat +
           risc_CVD_cat + LDL55PrevS_cat + LDL70PrevS_cat + LDL100PrevS_cat + LDL100PrevP_cat + LDL130PrevP_cat
           + tabac.valor,
           data=dades_prematch,
           extra.labels = c("","",""), 
           hide = "No",
           show.p.overall = F,
           show.n = T) %>% 
  export2md()




```


```{r descriptiva2, include=TRUE}

# formu<-formula_table1("Taula1",y="sexe",taulavariables = conductor)
# # 
# table1::table1(formu,data=dades,Overall=T)


table1::table1(~age + age_cat4 + age_cat5 + DG.AP + DG.AVC_H + DG.AVC_NH + DG.CI + 
    DG.DIS + DG.HTA + DG.IC + DG.AVC + DG.PrevSec + FF.ALTRES_AAG + 
    FF.ALTRESDIS + FF.ALTRESHTA + FF.ANT_VITK + FF.ANTCA + FF.ARA2 + 
    FF.BBK + FF.BG_Metformina + FF.CLOPI + FF.DIPI + FF.DIURETIC + 
    FF.ESTATINA + FF.ESTATINA_COMB + FF.EZE + FF.FIBRAT + FF.IECA + 
    FF.AAG + FF.ANTIHTA + FF.HIPOLIP + ALCOHOL.valor + CAC.valor + 
    cHDL.valor + CKDEPI.valor + cLDL.valor + CREATININA.valor + 
    cT.valor + EXCPROTEINA.valor + GLICADA.valor + GLUCOSA.valor + 
    IMC.valor + IMC.valor.cat5 + PAD.valor + PAS.valor + PES.valor + 
    TALLA.valor + TG.valor + score2 + regicor + PA_cat + HBA1C7_cat + 
    risc_CVD_cat + LDL55PrevS_cat + LDL70PrevS_cat + LDL100PrevS_cat + 
    LDL100PrevP_cat + LDL130PrevP_cat + tabac.valor | sexe, 
    data=dades_prematch,
    Overall=FALSE)



```





